# -*- coding: utf-8 -*-
"""smartadv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhVkIv9Vpcj2GYYMbNCLTYbIrlZjngdt
"""

import streamlit as st
import pandas as pd

# Simulated Data
students = pd.DataFrame({
    "Name": ["Alice Chen"],
    "GPA": [2.3],
    "Attendance": [78],
    "Risk Score": ["High"],
    "Goals": ["Improve GPA to 3.0"],
    "Notes": ["Missed 2 advising sessions"],
    "GPA History": ["3.0 -> 2.8 -> 2.5 -> 2.3"],
    "Attendance History": ["90% -> 85% -> 80% -> 78%"],
    "Risk History": ["Low -> Medium -> High"],
    "Goal History": ["None -> Improve GPA to 3.0"],
    "Advisory Notes History": ["Attended 1 -> Missed 1 -> Missed 2"]
})

st.set_page_config(page_title="Smart Advisor Assistant", layout="centered")
st.title("Smart Advisor Assistant")
st.subheader("AI-Powered Academic Risk Monitoring & Action Plans")
st.markdown("---")

# Sidebar
student_name = st.sidebar.selectbox("🔍 Select a student", students["Name"])
student = students[students["Name"] == student_name].iloc[0]

# Student Performance Summary
st.markdown("### 🎓 Student Performance Summary")
st.markdown(f"- **GPA:** {student['GPA']}")
st.markdown("  - GPA of 2.3 reflects academic decline. Indicates need for tutoring, course load review, and closer monitoring.")
st.markdown(f"- **Attendance:** {student['Attendance']}%")
st.markdown("  - Attendance below 80% shows disengagement. Student may need flexible support or incentives to attend.")
st.markdown(f"- **Risk Level:** {student['Risk Score']}")
st.markdown("  - High risk due to low GPA, poor attendance, and missed sessions. Requires urgent, multi-faceted support plan.")
st.markdown(f"- **Goals:** {student['Goals']}")
st.markdown("  - Student goal is positive. Needs to break it into short-term steps with progress checks.")
st.markdown(f"- **Advisor Notes:** {student['Notes']}")
st.markdown("  - Missed advising sessions suggest disengagement or barriers. Follow-up and flexibility are key.")

# Recommendations
def get_advice(risk):
    if risk == "High":
        return [
            "Immediate tutoring referrals",
            "Weekly advising check-ins",
            "Connect to mental health/counseling",
            "Set GPA target (e.g., 2.5 next semester)"
        ]
    elif risk == "Medium":
        return [
            "Career exploration support",
            "Stress management resources",
            "Monitor GPA monthly",
            "Advisor follow-up in 2 weeks"
        ]
    else:
        return [
            "Internship & honors advising",
            "Grad school prep resources",
            "Optional monthly check-ins"
        ]

st.markdown("### 💡 Advisor Recommendations")
for rec in get_advice(student['Risk Score']):
    st.markdown(f"- {rec}")

if student['Risk Score'] == 'High':
    st.markdown("""
    **Explanation:**
    - Tutoring builds academic foundation and confidence.
    - Weekly check-ins ensure accountability.
    - Mental health support helps address hidden stressors.
    - Setting achievable GPA targets motivates consistent effort.
    """)

# Historical Trends
st.markdown("### 🧾 Historical Trends")
st.markdown(f"- **GPA History:** {student['GPA History']}")
st.markdown("  - Trend shows consistent GPA decline. Student may lack foundational skills or be overwhelmed.")
st.markdown(f"- **Attendance History:** {student['Attendance History']}")
st.markdown("  - Decreasing attendance likely affects class comprehension. Barriers should be explored.")
st.markdown(f"- **Risk Level History:** {student['Risk History']}")
st.markdown("  - Risk level escalation indicates cumulative challenges. Must act fast to reverse the trend.")
st.markdown(f"- **Goal History:** {student['Goal History']}")
st.markdown("  - Goal improvement shows growing awareness. Advisors should build on this momentum.")
st.markdown(f"- **Advisory Notes History:** {student['Advisory Notes History']}")
st.markdown("  - Missed advising suggests disengagement or unmet needs. Offer flexible and proactive outreach.")

# AI Assistant Insight
st.markdown("### 🧠 AI Assistant Insight")
insight = f'''
- **GPA Decline:** {student["GPA History"]} -> Indicates long-term academic difficulty.
- **Attendance Drop:** {student["Attendance History"]} -> May signal disengagement or external factors.
- **Risk Escalation:** {student["Risk History"]} -> Multiple semesters of red flags.
- **Goal Evolution:** {student["Goal History"]} -> Shows increased focus or recognition of academic gap.
- **Advisory Notes:** {student["Advisory Notes History"]} -> Growing support needs.

GenAI Insight: Patterns suggest early-stage academic risk. A coordinated action plan is required combining academic, mental health, and advising strategies.
'''
st.info(insight)

# Advising Session Summary
st.markdown("### 📝 Advising Session Summary")
report = f'''
Advising Summary for {student_name}

- Risk Level: {student["Risk Score"]}
- Student Goals: {student["Goals"]}
- Advisor Notes: {student["Notes"]}

AI Advisor Recommendation:
{chr(10).join(get_advice(student["Risk Score"]))}

GenAI Insight:
{insight}
'''
st.text_area("Auto-Generated Report", value=report, height=300)
st.download_button("Download Session Report", data=report, file_name=f"{student_name}_advising_summary.txt", mime="text/plain")