# -*- coding: utf-8 -*-
"""smartadv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhVkIv9Vpcj2GYYMbNCLTYbIrlZjngdt
"""

import streamlit as st
import pandas as pd

# Simulated Dummy Data
students = pd.DataFrame({
    "Student ID": [1001, 1002, 1003],
    "Name": ["Alice Chen", "David Lee", "Sara Khan"],
    "GPA": [2.3, 3.5, 2.7],
    "Attendance": [78, 95, 85],
    "Risk Score": ["High", "Low", "Medium"],
    "Goals": ["Improve GPA to 3.0", "Graduate with honors", "Explore career in healthcare"],
    "Notes": ["Missed 2 advising sessions", "Engaged, on track", "Unclear on major, stressed in Chem"],
    "GPA History": ["2.5 -> 2.3", "3.4 -> 3.5", "3.0 -> 2.7"],
    "Attendance History": ["85% -> 78%", "93% -> 95%", "90% -> 85%"],
    "Risk History": ["Medium -> High", "Low -> Low", "Low -> Medium"],
    "Goal History": ["None -> Improve GPA to 3.0", "Same", "Undecided -> Explore healthcare"],
    "Advisory Notes History": ["1 missed -> 2 missed", "N/A", "New stress indicators in Chem"]
})

# Streamlit UI
st.set_page_config(page_title="Smart Advisor Assistant", layout="wide")
st.title("Smart Advisor Assistant")
st.subheader("AI-Powered Academic Risk Monitoring & Action Plans")
st.markdown("---")

# Sidebar Filters
student_name = st.sidebar.selectbox("🎓 Select a student", students["Name"])
student = students[students["Name"] == student_name].iloc[0]
st.sidebar.markdown("### 📈 Historical Data")
st.sidebar.write(f"**GPA History:** {student['GPA History']}")
st.sidebar.write(f"**Attendance History:** {student['Attendance History']}")
st.sidebar.write(f"**Risk Level History:** {student['Risk History']}")
st.sidebar.write(f"**Goal History:** {student['Goal History']}")
st.sidebar.write(f"**Advisory Notes History:** {student['Advisory Notes History']}")

# Student Summary
st.markdown("### 🧾 Student Performance Summary")
st.write(f"**GPA:** {student['GPA']}")
st.write(f"**Attendance:** {student['Attendance']}%")
st.write(f"**Risk Level:** {student['Risk Score']}")
st.write(f"**Goals:** {student['Goals']}")
st.write(f"**Advisor Notes:** {student['Notes']}")

# Recommendations
def get_advice(risk):
    if risk == "High":
        return "Immediate tutoring referrals\nWeekly advising check-ins\nConnect to mental health/counseling\nSet GPA target (e.g., 2.5 next semester)"
    elif risk == "Medium":
        return "Career exploration support\nStress management resources\nMonitor GPA monthly\nAdvisor follow-up in 2 weeks"
    else:
        return "Recommend internship & honors advising\nGrad school prep resources\nMonthly check-ins optional"

st.markdown("### 💡 Advisor Recommendations")
st.markdown(f"**{student['Risk Score']} Risk Plan:**")
st.markdown(get_advice(student["Risk Score"]).replace("\n", "\n- "), unsafe_allow_html=True)

# AI Assistant Insight
st.markdown("### 🤖 AI Assistant Insight")
insight_text = f"""
**Changes Detected:**
- GPA dropped from {student["GPA History"]} indicating academic struggle.
- Attendance decreased: {student["Attendance History"]} linked to engagement decline.
- Risk escalated: {student["Risk History"]} signals intervention need.
- Goal update: {student["Goal History"]} suggests changing motivation or clarity.
- Advisory Notes: {student["Advisory Notes History"]} require follow-up.

**AI Analysis:**
The historical trends reflect a change in performance and engagement. Recommend a proactive, multi-modal support plan: academic coaching, mental health referral, and goal-setting alignment.
"""
st.info(insight_text)

# Advising Report
st.markdown("### 📄 Advising Session Summary")
report = f"""
- Risk Level: {student['Risk Score']}
- Student Goals: {student['Goals']}
- Advisor Notes: {student['Notes']}

**AI Advisor Recommendation:**
**{student['Risk Score']} Risk Plan:**
{get_advice(student['Risk Score'])}
"""
st.text_area("Auto-Generated Report", value=report, height=250)
st.download_button("📥 Download Session Report", data=report, file_name=f"{student_name}_advising_summary.txt", mime="text/plain")